Update build imports

diff --git a/scripts/build_imports b/scripts/build_imports
--- a/scripts/build_imports
+++ b/scripts/build_imports
@@ -19,21 +19,24 @@ if [ ! -s "${wdl}" ]; then
     echo Given WDL "${wdl}" does not exist! && exit 2
 fi
 wdl_dn=$(readlink -f "${wdl}" | xargs -I% dirname %)
-echo  "${wdl_dn}"
 
 working_dn=$(mktemp -d 2>/dev/null || mktemp -d -t 'build-imports-XXX')
 echo WDL: "${wdl}"
+import_wdls=($(grep import "${wdl}" | awk -F\" '{print $2}'))
+if [ ${#import_wdls[*]} == 0 ]; then
+    echo "WDL has no imports, skipping!"
+    exit 0
+fi
 for import_wdl in $(grep import "${wdl}" | awk -F\" '{print $2}'); do
+    if [ ! -e ${import_wdl} ]; then
+        echo "Missing import [${import_wdl}], cannot build imports." 
+        exit 1
+    fi
     dest_bn=$(dirname ${import_wdl})
     dest_dn="${working_dn}/${dest_bn}"
     mkdir -p "${dest_dn}"
-    #cp "../${import_wdl}" ${dest_dn}
-    #import_wdl_imports="../${import_wdl/.wdl/.imports.zip}"
     cp "${import_wdl}" ${dest_dn}
     import_wdl_imports="${import_wdl/.wdl/.imports.zip}"
-    if [ -e "${import_wdl_imports}" ]; then
-        unzip -qo "${import_wdl_imports}" -d "${dest_dn}"
-    fi
 done
 
 prev_dn=$(pwd -P)
@@ -41,8 +44,7 @@ cd ${working_dn}
 zip_fn=$(basename "${wdl}" | sed 's/\.wdl/.imports.zip/')
 zip -qr "${zip_fn}" .
 wdl_dn=$(dirname "${wdl}")
-cd "${prev_dn}"
-cd "${wdl_dn}"
+cd "${prev_dn}/${wdl_dn}"
 cp -f "${working_dn}/${zip_fn}" .
 unzip -l "${zip_fn}"
 echo Created imports file: "${wdl_dn}/${zip_fn}"
